/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myjob1;

/**
 *
 * @author Frank
 */
public class TestJFrame extends javax.swing.JFrame
{
    int xMouse;
    int yMouse;

    /**
     * Creates new form TestJFrame
     */
    public TestJFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        FrameDragLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        New_UserButton = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        OrLabel = new javax.swing.JLabel();
        LogInButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        XbuttonPanel = new javax.swing.JPanel();
        XLabel = new javax.swing.JLabel();
        MinButtonPanel = new javax.swing.JPanel();
        MinButtLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SettingsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrameDragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                FrameDragLabelMouseDragged(evt);
            }
        });
        FrameDragLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                FrameDragLabelMousePressed(evt);
            }
        });
        jPanel2.add(FrameDragLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 20));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        New_UserButton.setBackground(new java.awt.Color(0, 0, 0));
        New_UserButton.setForeground(new java.awt.Color(51, 51, 51));
        New_UserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myjob1/Images/NewUser.png"))); // NOI18N
        New_UserButton.setBorder(null);
        New_UserButton.setBorderPainted(false);
        New_UserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        New_UserButton.setFocusPainted(false);
        New_UserButton.setMaximumSize(new java.awt.Dimension(147, 40));
        New_UserButton.setMinimumSize(new java.awt.Dimension(147, 40));
        New_UserButton.setPreferredSize(new java.awt.Dimension(147, 40));

        WelcomeLabel.setFont(new java.awt.Font("Castellar", 3, 14)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("Welcome");

        OrLabel.setFont(new java.awt.Font("Castellar", 3, 14)); // NOI18N
        OrLabel.setForeground(new java.awt.Color(255, 255, 255));
        OrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrLabel.setText("Or");

        LogInButton.setBackground(new java.awt.Color(0, 0, 0));
        LogInButton.setForeground(new java.awt.Color(51, 51, 51));
        LogInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myjob1/Images/Log In.png"))); // NOI18N
        LogInButton.setBorder(null);
        LogInButton.setBorderPainted(false);
        LogInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogInButton.setFocusPainted(false);
        LogInButton.setMaximumSize(new java.awt.Dimension(121, 35));
        LogInButton.setMinimumSize(new java.awt.Dimension(121, 35));
        LogInButton.setOpaque(false);
        LogInButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LogInButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Introduction for fitness application  which helps you . . .");
        jTextArea1.setToolTipText("");
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(OrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(New_UserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(OrLabel))))
                    .addComponent(New_UserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 700, 390));

        XbuttonPanel.setBackground(new java.awt.Color(0, 0, 0));
        XbuttonPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        XbuttonPanel.setRequestFocusEnabled(false);

        XLabel.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        XLabel.setForeground(new java.awt.Color(255, 0, 51));
        XLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XLabel.setText("X");
        XLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                XLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout XbuttonPanelLayout = new javax.swing.GroupLayout(XbuttonPanel);
        XbuttonPanel.setLayout(XbuttonPanelLayout);
        XbuttonPanelLayout.setHorizontalGroup(
            XbuttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );
        XbuttonPanelLayout.setVerticalGroup(
            XbuttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(XbuttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 20, 20));

        MinButtonPanel.setBackground(new java.awt.Color(0, 0, 0));
        MinButtonPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        MinButtonPanel.setPreferredSize(new java.awt.Dimension(20, 19));

        MinButtLabel.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        MinButtLabel.setForeground(new java.awt.Color(255, 0, 51));
        MinButtLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinButtLabel.setText("_");
        MinButtLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinButtLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                MinButtLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MinButtonPanelLayout = new javax.swing.GroupLayout(MinButtonPanel);
        MinButtonPanel.setLayout(MinButtonPanelLayout);
        MinButtonPanelLayout.setHorizontalGroup(
            MinButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
            .addGroup(MinButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MinButtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
        );
        MinButtonPanelLayout.setVerticalGroup(
            MinButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
            .addGroup(MinButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MinButtonPanelLayout.createSequentialGroup()
                    .addComponent(MinButtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.add(MinButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 20, 20));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.setPreferredSize(new java.awt.Dimension(20, 19));

        SettingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SettingsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myjob1/Images/settings.png"))); // NOI18N
        SettingsLabel.setMaximumSize(new java.awt.Dimension(15, 16));
        SettingsLabel.setMinimumSize(new java.awt.Dimension(15, 16));
        SettingsLabel.setPreferredSize(new java.awt.Dimension(15, 16));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SettingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SettingsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(720, 421));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LogInButtonActionPerformed
    {//GEN-HEADEREND:event_LogInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInButtonActionPerformed

    private void FrameDragLabelMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FrameDragLabelMouseDragged
    {//GEN-HEADEREND:event_FrameDragLabelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        //System.out.println(x + "," + y);
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameDragLabelMouseDragged

    private void XLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_XLabelMouseClicked
    {//GEN-HEADEREND:event_XLabelMouseClicked
       System.exit(0);
    }//GEN-LAST:event_XLabelMouseClicked

    private void MinButtLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_MinButtLabelMouseClicked
    {//GEN-HEADEREND:event_MinButtLabelMouseClicked
        this.setState(TestJFrame.ICONIFIED);
    }//GEN-LAST:event_MinButtLabelMouseClicked

    private void FrameDragLabelMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FrameDragLabelMousePressed
    {//GEN-HEADEREND:event_FrameDragLabelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TestJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameDragLabel;
    private javax.swing.JButton LogInButton;
    private javax.swing.JLabel MinButtLabel;
    private javax.swing.JPanel MinButtonPanel;
    private javax.swing.JButton New_UserButton;
    private javax.swing.JLabel OrLabel;
    private javax.swing.JLabel SettingsLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel XLabel;
    private javax.swing.JPanel XbuttonPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
